version: "3.5"
services:

  mysqls_ledger:
    image: mysql:8
    container_name: "mysql_container_for_ledger"
    volumes:
      - mysql-data-Ledger:/var/lib/mysql
    ports:
     - "3307:3306" 
    environment:
      - MYSQL_ROOT_PASSWORD=ledger@Kanzen2024
    networks:
      - scalar-network 
    healthcheck:
        test: "/usr/bin/mysql --user=root --password=ledger@Kanzen2024 --execute \"SHOW DATABASES;\""
        interval: 10s
        timeout: 60s
        retries: 15

  mysqls_auditor:
    image: mysql:8
    container_name: "mysql_container_for_auditor"
    volumes:
      - mysql-data-Auditor:/var/lib/mysql
    ports:
     - "3308:3306" 
    environment:
      - MYSQL_ROOT_PASSWORD=auditor@Kanzen2024
    networks:
      - scalar-network
    healthcheck:
        test: "/usr/bin/mysql --user=root --password=auditor@Kanzen2024 --execute \"SHOW DATABASES;\""
        interval: 10s
        timeout: 60s
        retries: 15

  scalardl-ledger-schema-loader-mysql-ledger:
    image: ghcr.io/scalar-labs/scalardl-schema-loader:3.10.0
    volumes:
      - ./scalardb-ledger.properties:/scalardb-ledger.properties
    depends_on:
      mysqls_ledger:
        condition: service_healthy
    command:
      - "-c"
      - "/scalardb-ledger.properties"
      - "--coordinator"
    networks:
      - scalar-network
    restart: on-failure

  scalar-ledger:
    image: ghcr.io/scalar-labs/scalardl-ledger-byol:3.10.0
    container_name: "scalardl-samples-scalar-ledger-1"
    volumes:
      - ./fixture/ledger-key.pem:/scalar/ledger-key.pem
      # - ./fixture/ledger.properties.tmpl:/scalar/ledger/ledger.properties.tmpl
      # - ./fixture/trial-license-cert.pem:/scalar/license-cert.pem
      # If you have a commercial license key, you must use `commercial-license-cert.pem` instead of `trial-license-cert.pem`.
      - ./fixture/ledger.properties.tmpl:/scalar/ledger/ledger.properties.tmpl
      - ./fixture/commercial-license-cert.pem:/scalar/license-cert.pem
    depends_on:
      scalardl-ledger-schema-loader-mysql-ledger:
        condition: service_completed_successfully
    environment:
      - SCALAR_DB_CONTACT_POINTS=jdbc:mysql://mysql_container_for_ledger:3306/
      - SCALAR_DB_STORAGE=jdbc
      - SCALAR_DB_USERNAME=root
      - SCALAR_DB_PASSWORD=ledger@Kanzen2024
      - SCALAR_DL_LEDGER_PROOF_ENABLED=true
      - SCALAR_DL_LEDGER_PROOF_PRIVATE_KEY_PATH=/scalar/ledger-key.pem
      - SCALAR_DL_LEDGER_AUDITOR_ENABLED=true

      ##### PLEASE REPLACE THIS VALUE WITH YOUR LICENSE KEY #####
      - SCALAR_DL_LICENSING_LICENSE_KEY={"organization_name":"Scalar Inc / Kanzen Demo","expiration_date_time":null,"product_name":"ScalarDL Ledger","product_version":3,"license_type":"enterprise","signature":"MEUCIA1lQhcSq+L3lqkLEd0jS5Dz2aKo62eH/bGSrHzcZ6zNAiEAiO0oETpadtevEWncdov3AW0xJ0UxYNAEOkak1Tn+7jA="}
      ##### PLEASE REPLACE THIS VALUE WITH YOUR LICENSE KEY #####

    networks:
      - scalar-network
    healthcheck:
      test: ["CMD-SHELL", "grpc_health_probe -addr=localhost:50051 && grpc_health_probe -addr=ledger-envoy:50051 || exit 1"]
      interval: 10s
      timeout: 20s
      retries: 60
      start_period: 15s

  ledger-envoy:
    image: ghcr.io/scalar-labs/scalar-envoy:1.5.0
    container_name: "scalardl-samples-ledger-envoy-1"
    ports:
      - "9901:9901"
      - "50051:50051"
      - "50052:50052"
    depends_on:
      scalar-ledger:
        condition: service_started
    environment:
      - admin_access_log_path=/dev/stdout
      - scalardl_address=scalar-ledger
      - service_listeners=scalar-service:50051,scalar-privileged:50052
      - envoy_tls=false
    networks:
      - scalar-network

  cfssl-init:
    # This service should be run separately before two services below
    # (cfssl-serve and cfssl-ocspserve) with `depends_on` option, because if
    # they start up at the same time (by commands like `docker-compose up`),
    # they both attempt to generate the same missing certificate files, which
    # results in a race condition.
    image: ghcr.io/scalar-labs/scalar-cfssl:1.0.0
    container_name: "scalardl-samples-cfssl-init-1"
    volumes:
      - ./cfssl/data:/cfssl/data
    command: /bin/true
    networks:
      - scalar-network

  cfssl-serve:
    image: ghcr.io/scalar-labs/scalar-cfssl:1.0.0
    container_name: "scalardl-samples-cfssl-serve-1"
    volumes:
      - ./cfssl/data:/cfssl/data
    depends_on:
      - cfssl-init
    command: serve
    ports:
      - "8888:8888"
    networks:
      - scalar-network

  cfssl-ocspserve:
    image: ghcr.io/scalar-labs/scalar-cfssl:1.0.0
    container_name: "scalardl-samples-cfssl-ocspserve-1"
    volumes:
      - ./cfssl/data:/cfssl/data
    depends_on:
      - cfssl-init
    command: ocspserve
    ports:
      - "8889:8889"
    networks:
      - scalar-network

  scalardl-auditor-schema-loader-mysql-auditor:
    image: ghcr.io/scalar-labs/scalardl-schema-loader:3.10.0
    environment:
      - SCHEMA_TYPE=auditor
    volumes:
      - ./scalardb-auditor.properties:/scalardb-auditor.properties
    depends_on:
      mysqls_auditor:
        condition: service_healthy
    command:
      - "-c"
      - "/scalardb-auditor.properties"
      - "--coordinator"
    networks:
      - scalar-network
    restart: on-failure

  scalar-ledger-as-client:
    image: ghcr.io/scalar-labs/scalar-client:3.10.0
    container_name: "scalardl-samples-scalar-ledger-as-client-1"
    volumes:
      - ./fixture/ledger.pem:/scalar/ledger.pem
      - ./fixture/ledger-key.pem:/scalar/ledger-key.pem
    depends_on:
      scalar-ledger:
        condition: service_healthy
      scalar-auditor:
        condition: service_healthy
    environment:
      - SCALAR_DL_CLIENT_SERVER_HOST=ledger-envoy
      - SCALAR_DL_CLIENT_AUDITOR_HOST=auditor-envoy
      - SCALAR_DL_CLIENT_AUDITOR_ENABLED=true
      - SCALAR_DL_CLIENT_CERT_HOLDER_ID=ledger
      - SCALAR_DL_CLIENT_CERT_PATH=/scalar/ledger.pem
      - SCALAR_DL_CLIENT_PRIVATE_KEY_PATH=/scalar/ledger-key.pem

    networks:
      - scalar-network
    command: |
      dockerize -template client.properties.tmpl:client.properties
      -template log4j2.properties.tmpl:log4j2.properties
      ./client/bin/register-cert --config client.properties
    restart: on-failure:5

  scalar-audior-as-client:
    image: ghcr.io/scalar-labs/scalar-client:3.10.0
    container_name: "scalardl-samples-scalar-auditor-as-client-1"
    volumes:
      - ./fixture/auditor.pem:/scalar/auditor.pem
      - ./fixture/auditor-key.pem:/scalar/auditor-key.pem
    depends_on:
      scalar-ledger:
        condition: service_healthy
      scalar-auditor:
        condition: service_healthy
    environment:
      - SCALAR_DL_CLIENT_SERVER_HOST=ledger-envoy
      - SCALAR_DL_CLIENT_AUDITOR_HOST=auditor-envoy
      - SCALAR_DL_CLIENT_AUDITOR_ENABLED=true
      - SCALAR_DL_CLIENT_CERT_HOLDER_ID=auditor
      - SCALAR_DL_CLIENT_CERT_PATH=/scalar/auditor.pem
      - SCALAR_DL_CLIENT_PRIVATE_KEY_PATH=/scalar/auditor-key.pem
    networks:
      - scalar-network
    command: |
      dockerize -template client.properties.tmpl:client.properties
      -template log4j2.properties.tmpl:log4j2.properties
      ./client/bin/register-cert --config client.properties
    restart: on-failure:5


  scalar-auditor:
    image: ghcr.io/scalar-labs/scalardl-auditor-byol:3.10.0
    container_name: "scalardl-samples-scalar-auditor-1"
    volumes:
      - ./fixture/auditor.pem:/scalar/auditor.pem
      - ./fixture/auditor-key.pem:/scalar/auditor-key.pem
      - ./fixture/auditor.properties.tmpl:/scalar/auditor/auditor.properties.tmpl
      # - ./fixture/trial-license-cert.pem:/scalar/license-cert.pem
      # If you have a commercial license key, you must use `commercial-license-cert.pem` instead of `trial-license-cert.pem`.
      - ./fixture/commercial-license-cert.pem:/scalar/license-cert.pem
    depends_on:
      scalardl-auditor-schema-loader-mysql-auditor:
        condition: service_completed_successfully
    environment:
      - SCALAR_DB_CONTACT_POINTS=jdbc:mysql://mysql_container_for_auditor:3306/
      - SCALAR_DB_STORAGE=jdbc
      - SCALAR_DB_USERNAME=root
      - SCALAR_DB_PASSWORD=auditor@Kanzen2024
      - SCALAR_DL_AUDITOR_LEDGER_HOST=ledger-envoy
      - SCALAR_DL_AUDITOR_CERT_PATH=/scalar/auditor.pem
      - SCALAR_DL_AUDITOR_PRIVATE_KEY_PATH=/scalar/auditor-key.pem

      ##### PLEASE REPLACE THIS VALUE WITH YOUR LICENSE KEY #####
      - SCALAR_DL_LICENSING_LICENSE_KEY={"organization_name":"Scalar Inc / Kanzen Demo","expiration_date_time":null,"product_name":"ScalarDL Auditor","product_version":3,"license_type":"enterprise","signature":"MEQCICI1WFioLv+xpPmInLT7JMWEQoqmVGvLBfqsLwCjjVlqAiAUT2baA4x3aweTu8dJRNebFAXwppvLxoN6ar2GFJO3eg=="}
      ##### PLEASE REPLACE THIS VALUE WITH YOUR LICENSE KEY #####

    networks:
      - scalar-network
    healthcheck:
      test: ["CMD-SHELL", "grpc_health_probe -addr=localhost:40051 && grpc_health_probe -addr=auditor-envoy:40051 || exit 1"]
      interval: 3s
      timeout: 15s
      retries: 60
      start_period: 10s

  auditor-envoy:
    image: ghcr.io/scalar-labs/scalar-envoy:1.5.0
    container_name: "scalardl-samples-auditor-envoy-1"
    ports:
      - "9902:9901"
      - "40051:40051"
      - "40052:40052"
    depends_on:
      scalar-auditor:
        condition: service_started
    environment:
      - admin_access_log_path=/dev/stdout
      - scalardl_address=scalar-auditor
      - service_listeners=scalar-service:40051,scalar-privileged:40052
      - envoy_tls=false
    networks:
      - scalar-network


volumes:
  mysql-data-Ledger:
  mysql-data-Auditor:

networks:
  scalar-network:
    name: scalar-network
