[[functions]]
function-id = "object.PutToMutableDatabase"
function-binary-name = "com.scalar.dl.genericcontracts.object.PutToMutableDatabase"
function-class-file = "build/classes/java/main/com/scalar/dl/genericcontracts/object/PutToMutableDatabase.class"
